---
- name: molecule verify
  hosts: all

  tasks:
    - name: Stat stns-cached sock
      ansible.builtin.stat:
        path: /var/run/cache-stnsd.sock
      register: cache_stnsd_sock
    - name: Verify stns-cached sock
      ansible.builtin.assert:
        that:
          - cache_stnsd_sock.stat.exists
