galaxy_info:
  author: stns
  description: STNS client role
  license: MIT
  min_ansible_version: '2.12'
  galaxy_tags: []
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
dependencies:
  - role: common
