---
- name: molecule converge
  hosts: all

  tasks:
    - name: include server role
      ansible.builtin.include_role:
        name: server
      vars:
        stns_server_config:
          port: 1105
