---
- name: molecule converge
  hosts: all

  tasks:
  - name: include client role
    ansible.builtin.include_role:
      name: takumakume.stns.client
  - name: include server role
    ansible.builtin.include_role:
      name: takumakume.stns.server
  - name: add sample user
    ansible.builtin.copy:
      src: user.conf
      dest: /etc/stns/server/conf.d/user.conf
      mode: '0644'
    notify: restart stns
