---
- name: create a STNS server directory
  ansible.builtin.file:
    path: /etc/stns/server/conf.d
    state: directory
    mode: '0755'

- name: config STNS server
  ansible.builtin.template:
    src: stns.conf.j2
    dest: /etc/stns/server/stns.conf
    mode: '0644'
  notify: restart stns
