---
- name: "{{ stns_server_state }} stns"
  ansible.builtin.package:
    name: "stns-v2{{ stns_version | default('') }}"
    state: "{{ stns_server_state }}"
  notify: restart stns

- name: start stns
  ansible.builtin.service:
    name: stns
    state: started
    enabled: true
  when: stns_server_state != 'absent'

- name: config stns server
  ansible.builtin.include_tasks: config.yml
  when: stns_server_state != 'absent'
