---
- name: molecule converge
  hosts: all

  tasks:
    - name: install server
      ansible.builtin.include_role:
        name: server
      vars:
        stns_server_state: latest
    - name: remove server
      ansible.builtin.include_role:
        name: server
      vars:
        stns_server_state: absent
