---
- name: (Debian/Ubuntu) add STNS repository key
  ansible.builtin.get_url:
    url: https://repo.stns.jp/gpg/GPG-KEY-stns
    dest: /etc/apt/keyrings/stns.asc
  become: true
- name: (Debian/Ubuntu) add STNS repository
  ansible.builtin.apt_repository:
    filename: stns
    repo: "deb [signed-by=/etc/apt/keyrings/stns.asc] https://repo.stns.jp/{{ ansible_distribution_release }}/ stns {{ ansible_distribution_release }}"
    mode: 0644
