---
- name: (Debian/Ubuntu) add STNS repository key
  apt_key:
    url: https://repo.stns.jp/gpg/GPG-KEY-stns
    state: present
  become: true
- name: (Debian/Ubuntu) add STNS repository
  ansible.builtin.apt_repository:
    filename: stns
    repo: "deb https://repo.stns.jp/{{ ansible_distribution_release }}/ stns {{ ansible_distribution_release }}"
    mode: 0644
