---
- name: install libnss-stns
  ansible.builtin.package:
    name: "libnss-stns-v2{{ libnss_stns_version | default('') }}"
    state: "{{ stns_client_state }}"

- name: install cache-stnsd
  ansible.builtin.package:
    name: "cache-stnsd{{ cache_stnsd_version | default('') }}"
    state: "{{ stns_client_state }}"
  notify: restart cache-stnsd

- name: start cache-stnsd
  ansible.builtin.service:
    name: cache-stnsd
    state: started
    enabled: true
  when: stns_client_state != "absent"

- name: stop cache-stnsd
  ansible.builtin.service:
    name: cache-stnsd
    state: stopped
    enabled: false
  when: stns_client_state == "absent"

- name: create a STNS client directory
  ansible.builtin.file:
    path: /etc/stns/client
    state: directory
    mode: '0755'
  when: stns_client_state != "absent"

- name: config STNS client
  ansible.builtin.template:
    src: stns.conf.j2
    dest: /etc/stns/client/stns.conf
    mode: '0644'
  when: stns_client_state != "absent"
