---
- name: "{{ stns_client_state }} libnss-stns"
  ansible.builtin.package:
    name: "libnss-stns-v2{{ libnss_stns_version | default('') }}"
    state: "{{ stns_client_state }}"

- name: "{{ stns_client_state }} cache-stnsd"
  ansible.builtin.package:
    name: "cache-stnsd{{ cache_stnsd_version | default('') }}"
    state: "{{ stns_client_state }}"
  notify: restart cache-stnsd

- name: start cache-stnsd
  ansible.builtin.service:
    name: cache-stnsd
    state: started
    enabled: true
  when: stns_client_state != 'absent'

- name: config stns client
  ansible.builtin.include_tasks: config.yml
  when: stns_client_state != 'absent'
